Feature/homework4
SonaArshakyan/.NETMentoringProgramAdvanced pull request #5
Opened 2023-11-22 11:50 UTC by SonaArshakyan

Implemented the interaction between Catalog and Basket services via a message broker (Azure Service Bus).
The message will be send to Azure Service Bus when Product will be updated from Catalog Service and BasketItemUpdater 
 from basket Service as BackgroundService will be responsible to update  the basket item in Basket Service side.

2023-12-04 18:14 UTC, krylatij requested changes
please re-organize services/interfaces and adjust exception handling, don't catch exceptions if you don't want to process them

2023-12-04 18:14 UTC, krylatij commented on Homework4/AzureServiceBusMessageBroker/Basket Service/Interfaces/Services/BasketItemUpdater.cs
> +public class BasketItemUpdater : BackgroundService
why it is inside Interfaces?

2023-12-04 18:14 UTC, krylatij commented on Homework4/AzureServiceBusMessageBroker/Basket Service/Interfaces/Services/BasketItemUpdater.cs
> +            _logger.LogError(ex.Message);
always log the full exception

2023-12-07 09:24 UTC, SonaArshakyan commented on Homework4/AzureServiceBusMessageBroker/Basket Service/Interfaces/Services/BasketItemUpdater.cs
> +public class BasketItemUpdater : BackgroundService
changed Initial logic and forgot to replace it

2023-12-15 18:25 UTC, merged